service: aws-ec2-monitor

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  region: your_region_here

functions:
  instanceEventHandler:
    handler: handler.lambda_handler
    role: IamRoleLambdaExecution
    environment:
      EMAIL_ADDRESSES: "email1@example.com,email2@example.com"
    #configure eventbridge to get treigered on start and terminate events 
    eevents:
      - cloudwatchEvent:
          name: "sre-ops-cw-ec2-alarm-rule"
          event:
            source:
              - 'aws.ec2'
            detail-type:
              - 'EC2 Instance State-change Notification'
            detail:
              state:
                - 'running'
                - 'terminated'
resources:
  Resources:
    SNSPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: SNSPublishPolicy
        Roles:
          - Ref: IamRoleLambdaExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"

    CWPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: CloudWatchPolicy
        Roles:
          - Ref: IamRoleLambdaExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
                - cloudwatch:PutMetricAlarm
              Resource: "*"

    EC2DescribePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: EC2DescribePolicy
        Roles:
          - Ref: IamRoleLambdaExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
              Resource: "*"

    LambdaBasicExecutionPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: LambdaBasicExecutionPolicy
        Roles:
          - Ref: IamRoleLambdaExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "arn:aws:logs:*:*:*"